import React, { useEffect, useMemo, useState } from "react";
import api from "../lib/api";
import { ShieldCheck, Building2, Users, KeyRound, Network, FlaskConical, Plus, RefreshCw, Trash2 } from "lucide-react";
import { toast } from "sonner";

const field = "w-full px-4 py-2.5 rounded-lg bg-[#0a0d14]/80 border border-white/10 text-sm";
const button = "w-full py-3 rounded-lg bg-yellow-500 text-black font-bold hover:bg-yellow-400 flex items-center justify-center gap-2";

export default function AccessControlPage() {
  const [data, setData] = useState({ organizations: [], roles: [], permissions: [], assignments: [], users: [] });
  const [tab, setTab] = useState("overview");
  const [org, setOrg] = useState({ name: "", code: "", kind: "department", parent_id: "" });
  const [role, setRole] = useState({ name: "", code: "", description: "", permissions: [], clearance: "internal", active: true });
  const [assignment, setAssignment] = useState({ user_id: "", role_id: "", scope_type: "global", scope_id: "", expires_at: "" });
  const [simulation, setSimulation] = useState({ user_id: "", action: "project.view", resource: { classification: "internal" }, context: { mfa_verified: true } });
  const [decision, setDecision] = useState(null);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    setLoading(true);
    try { setData((await api.get("/access/bootstrap")).data); }
    catch (e) { toast.error(e?.response?.data?.detail || "Unable to load Access Fabric"); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const users = useMemo(() => Object.fromEntries(data.users.map(x => [x.id, x])), [data.users]);
  const roles = useMemo(() => Object.fromEntries(data.roles.map(x => [x.id, x])), [data.roles]);
  const orgs = useMemo(() => Object.fromEntries(data.organizations.map(x => [x.id, x])), [data.organizations]);

  const createOrg = async e => { e.preventDefault(); await api.post("/access/organizations", { ...org, parent_id: org.parent_id || null }); toast.success("Unit created"); setOrg({ name: "", code: "", kind: "department", parent_id: "" }); load(); };
  const createRole = async e => { e.preventDefault(); await api.post("/access/roles", role); toast.success("Role created"); setRole({ name: "", code: "", description: "", permissions: [], clearance: "internal", active: true }); load(); };
  const createAssignment = async e => { e.preventDefault(); await api.post("/access/assignments", { ...assignment, group_id: null, scope_id: assignment.scope_id || null, expires_at: assignment.expires_at || null, starts_at: null }); toast.success("Scoped role assigned"); load(); };
  const revoke = async id => { await api.delete(`/access/assignments/${id}`); toast.success("Assignment revoked"); load(); };
  const runSimulation = async e => { e.preventDefault(); setDecision((await api.post("/access/simulate", simulation)).data); };

  if (loading) return <div className="p-8 text-slate-400">Loading ARAAK Access Fabric...</div>;

  const tabs = [["overview", ShieldCheck, "Overview"], ["structure", Building2, "Structure"], ["roles", KeyRound, "Roles"], ["assignments", Network, "Assignments"], ["simulator", FlaskConical, "Simulator"]];

  return <div className="space-y-6" data-testid="access-control-page">
    <div className="flex items-end justify-between gap-4 flex-wrap">
      <div><div className="text-xs uppercase tracking-[0.3em] text-yellow-500/80">ARAAK Access Fabric</div><h1 className="font-heading text-4xl font-black mt-2 flex items-center gap-3"><ShieldCheck className="text-yellow-500"/> Identity, Scope & Policy</h1><p className="text-slate-500 text-sm mt-2">Hybrid RBAC, organizational scope, temporary delegation, classifications, and explainable decisions.</p></div>
      <button onClick={load} className="px-4 py-2 rounded-lg border border-white/10 hover:bg-white/5 flex items-center gap-2"><RefreshCw size={16}/>Refresh</button>
    </div>

    <div className="flex gap-2 flex-wrap border-b border-white/5 pb-3">{tabs.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={`px-4 py-2 rounded-lg text-sm flex items-center gap-2 ${tab === id ? "bg-yellow-500/10 border border-yellow-500/20 text-yellow-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={15}/>{label}</button>)}</div>

    {tab === "overview" && <div className="grid md:grid-cols-4 gap-4">{[["Units", data.organizations.length, Building2], ["Role templates", data.roles.length, KeyRound], ["Assignments", data.assignments.filter(a => a.active !== false).length, Network], ["Users", data.users.length, Users]].map(([label, value, Icon]) => <div key={label} className="glass-card p-5"><Icon className="text-yellow-500 mb-4"/><div className="text-3xl font-black">{value}</div><div className="text-xs uppercase tracking-widest text-slate-500 mt-1">{label}</div></div>)}<div className="md:col-span-4 glass-card p-6"><h2 className="font-bold text-xl mb-4">Decision chain</h2><div className="grid md:grid-cols-5 gap-3">{["Identity", "Role", "Scope", "Relationship", "Context & policy"].map((x, i) => <div key={x} className="rounded-lg border border-white/10 p-4"><div className="text-yellow-400 text-xs mb-2">0{i+1}</div>{x}</div>)}</div></div></div>}

    {tab === "structure" && <div className="grid lg:grid-cols-[1fr_380px] gap-5"><div className="glass-card p-5 space-y-2">{data.organizations.map(x => <div key={x.id} className="flex justify-between rounded-lg border border-white/5 p-3"><div><div className="font-medium">{x.name}</div><div className="text-xs text-slate-500">{x.kind} · {x.code}</div></div><div className="text-xs text-slate-600">{x.parent_id ? orgs[x.parent_id]?.name : "Root"}</div></div>)}</div><form onSubmit={createOrg} className="glass-card p-5 space-y-3"><h2 className="font-bold text-lg">Add organizational unit</h2><input required className={field} placeholder="Unit name" value={org.name} onChange={e=>setOrg({...org,name:e.target.value})}/><input required className={field} placeholder="Unique code" value={org.code} onChange={e=>setOrg({...org,code:e.target.value.toUpperCase()})}/><select className={field} value={org.kind} onChange={e=>setOrg({...org,kind:e.target.value})}>{["company","department","branch","committee","project","team"].map(x=><option key={x}>{x}</option>)}</select><select className={field} value={org.parent_id} onChange={e=>setOrg({...org,parent_id:e.target.value})}><option value="">No parent</option>{data.organizations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className={button}><Plus size={16}/>Create unit</button></form></div>}

    {tab === "roles" && <div className="grid lg:grid-cols-[1fr_420px] gap-5"><div className="space-y-3">{data.roles.map(r => <div key={r.id} className="glass-card p-5"><div className="flex justify-between"><div><div className="font-bold text-lg">{r.name}</div><div className="text-xs text-slate-500">{r.code}{r.system ? " · System" : ""}</div></div><span className="text-xs">{r.permissions?.length || 0} permissions</span></div><p className="text-sm text-slate-400 mt-3">{r.description}</p><div className="flex gap-1 flex-wrap mt-3">{r.permissions?.slice(0,10).map(p=><span key={p} className="text-[10px] px-2 py-1 rounded bg-yellow-500/5 text-yellow-300">{p}</span>)}</div></div>)}</div><form onSubmit={createRole} className="glass-card p-5 space-y-3 h-fit"><h2 className="font-bold text-lg">Create role template</h2><input required className={field} placeholder="Role name" value={role.name} onChange={e=>setRole({...role,name:e.target.value})}/><input required className={field} placeholder="role_code" value={role.code} onChange={e=>setRole({...role,code:e.target.value.toLowerCase().replace(/\s+/g,"_")})}/><textarea className={field} placeholder="Description" value={role.description} onChange={e=>setRole({...role,description:e.target.value})}/><div className="max-h-64 overflow-y-auto rounded-lg border border-white/5 p-3 space-y-2">{data.permissions.map(p=><label key={p.code} className="flex gap-2 text-xs"><input type="checkbox" checked={role.permissions.includes(p.code)} onChange={e=>setRole({...role,permissions:e.target.checked?[...role.permissions,p.code]:role.permissions.filter(x=>x!==p.code)})}/>{p.code}</label>)}</div><button className={button}><Plus size={16}/>Create role</button></form></div>}

    {tab === "assignments" && <div className="space-y-5"><form onSubmit={createAssignment} className="glass-card p-5 grid md:grid-cols-3 gap-3"><select required className={field} value={assignment.user_id} onChange={e=>setAssignment({...assignment,user_id:e.target.value})}><option value="">Select user</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select><select required className={field} value={assignment.role_id} onChange={e=>setAssignment({...assignment,role_id:e.target.value})}><option value="">Select role</option>{data.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select className={field} value={assignment.scope_type} onChange={e=>setAssignment({...assignment,scope_type:e.target.value})}>{["global","organization","unit","project","resource"].map(x=><option key={x}>{x}</option>)}</select><select className={field} value={assignment.scope_id} onChange={e=>setAssignment({...assignment,scope_id:e.target.value})}><option value="">All / root</option>{data.organizations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={field} type="datetime-local" value={assignment.expires_at} onChange={e=>setAssignment({...assignment,expires_at:e.target.value})}/><button className={button}><Plus size={16}/>Assign role</button></form><div className="glass-card p-2 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b border-white/5"><th className="p-3">User</th><th>Role</th><th>Scope</th><th>Expiry</th><th></th></tr></thead><tbody>{data.assignments.filter(a=>a.active!==false).map(a=><tr key={a.id} className="border-b border-white/5"><td className="p-3">{users[a.user_id]?.name || "Group"}</td><td>{roles[a.role_id]?.name}</td><td>{a.scope_type} · {orgs[a.scope_id]?.name || "All"}</td><td>{a.expires_at ? new Date(a.expires_at).toLocaleString() : "Open-ended"}</td><td><button onClick={()=>revoke(a.id)} className="p-2 text-rose-300"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></div>}

    {tab === "simulator" && <div className="grid lg:grid-cols-2 gap-5"><form onSubmit={runSimulation} className="glass-card p-6 space-y-4"><h2 className="font-bold text-xl">Explain a decision</h2><select required className={field} value={simulation.user_id} onChange={e=>setSimulation({...simulation,user_id:e.target.value})}><option value="">Select user</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select><select className={field} value={simulation.action} onChange={e=>setSimulation({...simulation,action:e.target.value})}>{data.permissions.map(p=><option key={p.code}>{p.code}</option>)}</select><select className={field} value={simulation.resource.classification} onChange={e=>setSimulation({...simulation,resource:{...simulation.resource,classification:e.target.value}})}>{["internal","restricted","confidential","executive_secret","financial_sensitive","legal_privileged"].map(x=><option key={x}>{x}</option>)}</select><label className="flex gap-2 text-sm"><input type="checkbox" checked={simulation.context.mfa_verified} onChange={e=>setSimulation({...simulation,context:{...simulation.context,mfa_verified:e.target.checked}})}/>MFA verified</label><button className={button}><FlaskConical size={16}/>Evaluate</button></form><div className="glass-card p-6">{decision ? <><div className={`text-3xl font-black ${decision.allowed?"text-emerald-400":"text-rose-400"}`}>{decision.allowed ? "ALLOWED" : "DENIED"}</div><div className="mt-5 space-y-2">{decision.reasons.map((r,i)=><div key={i} className="rounded-lg border border-white/5 p-3 text-sm">{r}</div>)}</div><div className="text-xs text-slate-500 mt-4">Matched roles: {decision.matched_roles.join(", ") || "None"}</div></> : <div className="text-slate-500">Run a simulation to see the exact reason for allow or deny.</div>}</div></div>}
  </div>;
}
